
name: 'JSON‑VIPB'
description: 'Convert NI VIPB files ↔ JSON, apply YAML patches, optionally auto‑commit & PR.'
author: 'Sergio Velderrain Ruiz'
inputs:
  mode:
    description: 'vipb2json | json2vipb | patch2vipb'
    required: true
  args:
    description: 'Arguments to pass after mode (see README)'
    required: true
  patch_file:
    description: 'Path to YAML patch file (patch modes only)'
    required: false
  patch_yaml:
    description: 'Inline YAML patch string'
    required: false
  always_patch_fields:
    description: 'YAML mapping always applied (Company, Author, etc.)'
    required: false
  branch_name:
    description: 'If set, create branch & commit outputs'
    required: false
  auto_open_pr:
    description: 'true to open PR after push'
    required: false
  upload_files:
    description: 'Newline‑separated list of files to upload as artifacts'
    required: false
runs:
  using: 'docker'
  image: 'ghcr.io/svelderrainruiz/json-vipb:v1.2.0'
  args:
    - ${{ inputs.mode }}
    - ${{ inputs.args }}
    - ${{ inputs.patch_file }}
    - ${{ inputs.patch_yaml }}
    - ${{ inputs.always_patch_fields }}
    - ${{ inputs.branch_name }}
    - ${{ inputs.auto_open_pr }}
    - ${{ inputs.upload_files }}
