<Solution xmlns:i="http://www.w3.org/2001/XMLSchema-instance" z:Id="i1" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/" xmlns="http://schemas.datacontract.org/2004/07/NationalInstruments.PackageBuilder.Engine">
    <Name>seed</Name>
    <SourceItems />
    <InputSourceItems />
    <Distributions>
        <Distribution z:Id="i2" i:type="Package">
            <DistributionItems />
            <Name>New Package</Name>
            <OutputDirectory>Packages</OutputDirectory>
            <PluginConfigurationOptions />
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <Architecture>windows_x64</Architecture>
            <AutoIncrementVersion>Build</AutoIncrementVersion>
            <BuildStatus z:Id="i3">
                <FileName />
                <Version>none</Version>
            </BuildStatus>
            <CompanyName>MyCompany</CompanyName>
            <CustomExecutes />
            <DisplayName>New Package</DisplayName>
            <FileName>mycompany-myproduct_1.0.0.0_windows_x64.nipkg</FileName>
            <MaintainerEmail>email@mycompany.com</MaintainerEmail>
            <MaintainerName>MyCompany</MaintainerName>
            <Messages xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
            <PackageName>mycompany-myproduct</PackageName>
            <PackageRelationships />
            <ProductName>MyProduct</ProductName>
            <Section>Application Software</Section>
            <Synopsis>mycompany-myproduct</Synopsis>
            <Version>1.0.0.0</Version>
        </Distribution>
    </Distributions>
    <Feeds />
    <DistributionGroups>
        <DistributionGroup z:Id="i4">
            <Distributions>
                <Distribution z:Ref="i2" />
            </Distributions>
            <Name>Distribution Group</Name>
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <StageDirectory>ProcessingStage</StageDirectory>
        </DistributionGroup>
    </DistributionGroups>
    <TestStandMode>true</TestStandMode>
    <PluginConfigurationOptions />
</Solution>