name: build-release-assets
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: 8.0.x }
      - run: dotnet publish src/VipbJsonTool   -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true -o publish
      - run: dotnet publish src/LvprojJsonTool -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true -o publish

      # If you want to use wrapper scripts:
      - run: chmod +x bin/vipb2json bin/json2vipb bin/lvproj2json bin/json2lvproj bin/buildspec2json bin/json2buildspec
      - name: Install CLI binaries system-wide
        run: |
          sudo cp publish/VipbJsonTool   /usr/local/bin/VipbJsonTool
          sudo cp publish/LvprojJsonTool /usr/local/bin/LvprojJsonTool
          sudo chmod +x /usr/local/bin/VipbJsonTool /usr/local/bin/LvprojJsonTool

      # (Or skip the two steps above, and see below to call publish binaries directly)

      - name: Install yq
        run: sudo apt-get update && sudo apt-get -y install yq

      - name: Generate seed JSON/YAML
        run: |
          mkdir -p release
          ./bin/vipb2json  --input tests/Samples/seed.vipb   --output release/seed-vipb.json
          ./bin/lvproj2json --input tests/Samples/seed.lvproj --output release/seed-lvproj.json
          yq -p json -o yaml release/seed-vipb.json   > release/seed-vipb.yaml
          yq -p json -o yaml release/seed-lvproj.json > release/seed-lvproj.yaml
        # OR, skipping the wrappers:
        # run: |
        #   mkdir -p release
        #   publish/VipbJsonTool   --input tests/Samples/seed.vipb   --output release/seed-vipb.json
        #   publish/LvprojJsonTool --input tests/Samples/seed.lvproj --output release/seed-lvproj.json
        #   yq -p json -o yaml release/seed-vipb.json   > release/seed-vipb.yaml
        #   yq -p json -o yaml release/seed-lvproj.json > release/seed-lvproj.yaml

      - uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: |
            publish/VipbJsonTool
            publish/LvprojJsonTool
            release/seed-*.json
            release/seed-*.yaml
