name: build-test-release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/*.sln

      # --- VipbJsonTool Build/Publish ---
      - name: Restore .NET packages (VipbJsonTool)
        run: dotnet restore src/VipbJsonTool/VipbJsonTool.csproj

      - name: Build .NET project (VipbJsonTool)
        run: dotnet build src/VipbJsonTool/VipbJsonTool.csproj -c Release --no-restore -p:TreatWarningsAsErrors=false

      - name: Publish CLI (VipbJsonTool, linux-x64 single-file)
        run: dotnet publish src/VipbJsonTool -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true --no-restore --no-build -o publish/linux-x64

       # --- LvprojJsonTool Build/Publish ---
      - name: Restore .NET packages (LvprojJsonTool)
        run: dotnet restore src/LvprojJsonTool/LvprojJsonTool.csproj

      - name: Build .NET project (LvprojJsonTool)
        run: dotnet build src/LvprojJsonTool/LvprojJsonTool.csproj -c Release --no-restore -p:TreatWarningsAsErrors=false

      - name: Publish CLI (LvprojJsonTool, linux-x64 single-file)
        run: dotnet publish src/LvprojJsonTool -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true -p:TreatWarningsAsErrors=false --no-restore --no-build -o publish/linux-x64

      - name: Ensure bin/ directory exists and is writeable
        run: |
          mkdir -p bin
          chmod 777 bin

      - name: Copy published VipbJsonTool to bin
        run: Copy-Item -Force publish/linux-x64/VipbJsonTool bin/

      - name: Copy LvprojJsonTool binary to bin/
        run: Copy-Item -Force publish/linux-x64/LvprojJsonTool bin/

      # --- Pester Test & Coverage ---
      - name: Install Pester
        run: Install-Module Pester -Force -Scope CurrentUser

      - name: Run all Pester tests with coverage
        run: |
          $Config = New-PesterConfiguration
          $Config.Run.Path = 'tests'
          $Config.CodeCoverage.Enabled = $true
          $Config.CodeCoverage.Path = 'tools/*.ps1'
          $Config.TestResult.Enabled = $true
          $Config.TestResult.OutputFormat = 'NUnitXml'
          $Config.TestResult.OutputPath = 'test-results.xml'
          Invoke-Pester -Configuration $Config
          if ($LASTEXITCODE -ne 0) { exit 1 }

      # --- Upload Artifacts ---
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml

      - name: Upload seed-vipb.yaml artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: seed-vipb.yaml
          path: release/seed-vipb.yaml

      - name: Upload seed-lvproj.yaml artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: seed-lvproj.yaml
          path: release/seed-lvproj.yaml

      - name: Upload VipbJsonTool CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: vipb-json-cli-linux-x64
          path: publish/linux-x64/VipbJsonTool

      - name: Upload LvprojJsonTool CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: lvproj-json-cli-linux-x64
          path: publish/linux-x64/LvprojJsonTool

      # --- Optional: Build Docker Image ---
      - name: Build Docker image (for manual test or release)
        run: |
          docker build -t labview-seed:ci .
        # Add a docker push step here if you want to push to a registry

