name: build-test-release

on:
  push:
    branches: [ main ]
    tags:  [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/*.sln

      - name: Restore .NET packages
        run: dotnet restore src/VipbJsonTool/VipbJsonTool.csproj

      - name: Build .NET project
        run: dotnet build src/VipbJsonTool/VipbJsonTool.csproj -c Release --no-restore -p:TreatWarningsAsErrors=false

      - name: Publish CLI (linux-x64 single-file)
        run: dotnet publish src/VipbJsonTool -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true -p:TreatWarningsAsErrors=false --no-restore --no-build -o publish/linux-x64

      - name: Install Pester
        run: Install-Module Pester -Force -Scope CurrentUser

      - name: Run Golden Sample test (YAML generation)
        run: |
          $result = Invoke-Pester -Configuration @{
            Run = @{ Path = 'tests/RoundTrip.GoldenSample.Tests.ps1'; PassThru = $true }
            TestResult = @{ Enabled = $true; OutputFormat = 'NUnitXml'; OutputPath = 'golden-sample-results.xml' }
          }
          if ($result.FailedCount -gt 0) { exit 1 }

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: golden-sample-test-results
          path: golden-sample-results.xml

      - name: Upload seed-vipb.yaml artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: seed-vipb.yaml
          path: release/seed-vipb.yaml

      - name: Upload seed-lvproj.yaml artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: seed-lvproj.yaml
          path: release/seed-lvproj.yaml

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: vipb-json-cli-linux-x64
          path: publish/linux-x64/VipbJsonTool
