name: build-test-release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      # --- source code ---------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- .NET SDK ------------------------------------------------------------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/*.sln

      # --- restore & build -----------------------------------------------------
      - name: Restore packages
        run: dotnet restore src/VipbJsonTool/VipbJsonTool.csproj

      - name: Build (warnings ≠ errors)
        run: dotnet build src/VipbJsonTool/VipbJsonTool.csproj `
                          -c Release `
                          -p:TreatWarningsAsErrors=false `
                          --no-restore

      # --- publish single-file CLI ---------------------------------------------
      - name: Publish CLI (linux-x64 single-file)
        run: dotnet publish src/VipbJsonTool `
                            -c Release `
                            -r linux-x64 `
                            --self-contained `
                            -p:PublishSingleFile=true `
                            -p:TreatWarningsAsErrors=false `
                            --no-restore `
                            --no-build `
                            -o publish/linux-x64

      # --- PowerShell test prerequisites ---------------------------------------
      - name: Install Pester
        run: Install-Module Pester -Force -Scope CurrentUser

      - name: Run Pester tests (Basic and Full Golden Sample Coverage)
        run: |
          Invoke-Pester tests/RoundTrip.Tests.ps1 -CI -OutputFile basic-test-results.xml -OutputFormat NUnitXml
          Invoke-Pester tests/RoundTrip.GoldenSample.Tests.ps1 -CI -Script @{
            Parameters = @{ SourceFile = "tests/Samples/seed.vipb" }
          } -OutputFile golden-sample-results.xml -OutputFormat NUnitXml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pester-test-results
          path: |
            basic-test-results.xml
            golden-sample-results.xml

      # --- Docker image (main branch and tags only) ----------------------------
      - name: Build Docker image
        run: docker build -t ghcr.io/labview-community-ci-cd/seed:${{ github.sha }} .

      - name: Docker login, tag & push (main & tags only)
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Tag Docker images
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag ghcr.io/labview-community-ci-cd/seed:${{ github.sha }} ghcr.io/labview-community-ci-cd/seed:latest
          docker tag ghcr.io/labview-community-ci-cd/seed:${{ github.sha }} ghcr.io/labview-community-ci-cd/seed:${{ github.ref_name }}

      - name: Push Docker images
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        run: |
          docker push ghcr.io/labview-community-ci-cd/seed:${{ github.sha }}
          docker push ghcr.io/labview-community-ci-cd/seed:latest
          docker push ghcr.io/labview-community-ci-cd/seed:${{ github.ref_name }}

      # --- artifact upload ------------------------------------------------------
      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: vipb-json-cli-linux-x64
          path: publish/linux-x64/VipbJsonTool
