name: build‑test‑release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh        # every run block uses PowerShell 7

    steps:
    # --- source code ---------------------------------------------------------
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # --- .NET SDK ------------------------------------------------------------
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: |
          **/*.csproj
          **/*.sln

# --- restore & build -----------------------------------------------------
    - name: Restore packages
      run: dotnet restore src/VipbJsonTool/VipbJsonTool.csproj

    - name: Build (warnings ≠ errors)
      run: dotnet build src/VipbJsonTool/VipbJsonTool.csproj `
                        -c Release `
                        -p:TreatWarningsAsErrors=false `
                        --no-restore

    # --- publish single‑file CLI --------------------------------------------
    - name: Publish CLI (linux‑x64 single‑file)
      run: dotnet publish src/VipbJsonTool `
                          -c Release `
                          -r linux-x64 `
                          --self-contained `
                          -p:PublishSingleFile=true `
                          -p:TreatWarningsAsErrors=false `
                          --no-restore `
                          --no-build `
                          -o publish/linux-x64

    # --- PowerShell test prerequisites --------------------------------------
    - name: Install PowerShell modules
      run: |
        Install-Module PowerShell-Yaml -RequiredVersion 0.4.2 -Scope CurrentUser -Force
        Install-Module Pester          -Scope CurrentUser -Force

    # --- generate patch + run tests -----------------------------------------
    - name: Generate patch template & run Pester tests
      shell: pwsh
      run: |
        $vipb = "./tests/Samples/NI Icon editor.vipb"
        $json = "./tmp.json"

        # 1. VIPB -> JSON
        ./publish/linux-x64/VipbJsonTool vipb2json "$vipb" "$json"

        # 2. Enumerate all JSON paths
        ./tools/Enumerate-VipbPaths.ps1 "$json" | Set-Content paths.txt

        # 3. Build YAML patch file (ensure at least ONE entry)
        $patchLines = @(
          'schema_version: 1',
          'patch:'
        )

        foreach ($p in Get-Content paths.txt) {
          if ($p -match '\[\d+\]')      { $patchLines += "  $p: '__ARRAY__'" }
          elseif ($p -match '@')        { $patchLines += "  $p: 'TEST'"      }
          elseif ($p -in 'true','false'){ $patchLines += "  $p: true"        }
          else                          { $patchLines += "  $p: 'TEST'"      }
        }

        # Fallback: guarantee at least one entry if something went wrong
        if ($patchLines.Count -le 2) {
          $patchLines += '  Library_General_Settings.Company_Name.__text: ""'
        }

        $patchFile = "ci-patch-full.yml"
        $patchLines | Set-Content -Encoding utf8 $patchFile
        Write-Host "Generated patch file with $($patchLines.Count-2) entries"

        # 4. Decide which tests to run
        if ((Get-Content $patchFile | Where-Object { $_ -match '^\s{2}\S' }).Count -eq 0) {
          Write-Warning "Patch map is empty – running only round‑trip test."
          Invoke-Pester tests/RoundTrip.Tests.ps1 -CI
        }
        else {
          # run both full and selective patch tests
          Invoke-Pester tests/RoundTrip.Full.Tests.ps1 -CI -Passthru `
            -Data @{ PatchFile=$patchFile; SourceVipb=$vipb }
          Invoke-Pester tests/RoundTrip.Deep.Tests.ps1 -CI -Passthru  `
            -Data @{ PatchFile=$patchFile; SourceVipb=$vipb }
        }


    # --- Docker image (optional) --------------------------------------------
    - name: Build Docker image
      run: docker build -t vipb-json:${{ github.sha }} .

    # --- artefact upload -----------------------------------------------------
    - name: Upload CLI artefact
      uses: actions/upload-artifact@v4
      with:
        name: vipb-json-cli-linux-x64
        path: publish/linux-x64/VipbJsonTool
