name: build-test-release

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore & build
        run: dotnet build src/VipbJsonTool/VipbJsonTool.csproj -c Release

      - name: Publish self‑contained single file (linux‑x64)
        run: dotnet publish src/VipbJsonTool -c Release -r linux-x64 --self-contained -o publish/linux-x64-singlefile

      # ---------- prepare round‑trip files for deep patch test ----------
      - name: Generate round‑trip artefacts
        shell: pwsh
        run: |
          dotnet run --project src/VipbJsonTool -- vipb2json 'tests/Samples/NI Icon editor.vipb' tmp.json
          dotnet run --project src/VipbJsonTool -- patch2vipb tmp.json tmp.vipb ci-patch.yml '' ''
          dotnet run --project src/VipbJsonTool -- vipb2json tmp.vipb tmp2.json

      # ---------- tests ----------
      - name: Run Pester tests
        shell: pwsh
        run: |
          Install-Module Pester -Force -Scope CurrentUser
          Register-PSRepository -Default -ErrorAction SilentlyContinue
          Install-Module PowerShell.Yaml -Force -Scope CurrentUser
          Invoke-Pester tests -CI
          Invoke-Pester tests/RoundTrip.Deep.Tests.ps1

      - name: Build Action image
        run: docker build -t vipb-json:${{ github.sha }} .

      - uses: actions/upload-artifact@v4
        with:
          name: vipb-json-cli
          path: publish/linux-x64-singlefile/VipbJsonTool
